"""create event_types table

Revision ID: 115c9c8d7f3a
Revises: 73d28fa2b62d
Create Date: 2026-10-04 18:34:23.278717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '115c9c8d7f3a'
down_revision: Union[str, Sequence[str], None] = '73d28fa2b62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostId', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('durationMinutes', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('locationType', sa.Text(), server_default='online', nullable=False),
    sa.Column('locationValue', sa.Text(), nullable=True),
    sa.Column('bufferBeforeMinutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bufferAfterMinutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['hostId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostId', 'slug', name='uq_event_types_host_slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_types')
    # ### end Alembic commands ###
