"""create availability_exceptions table

Revision ID: 33e599cb545c
Revises: 0450e5153ed8
Create Date: 2026-10-04 23:49:35.020017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33e599cb545c'
down_revision: Union[str, Sequence[str], None] = '0450e5153ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_exceptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('startTime', sa.Text(), nullable=True),
    sa.Column('endTime', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), server_default='UTC', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_availability_exceptions_user_date', 'availability_exceptions', ['userId', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_availability_exceptions_user_date', table_name='availability_exceptions')
    op.drop_table('availability_exceptions')
    # ### end Alembic commands ###
